apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: my-user
  labels:
    strimzi.io/cluster: strimzi-kafka
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: test
          patternType: literal
        operations:
          - Describe
          - Read
          - Write
          - Create
          - Delete
          - Alter
      - resource:
          type: group
          name: telegraf_metrics_consumers
          patternType: literal
        operations:
          - Describe
          - Read
          - Write
          - Create
          - Delete
          - Alter
